WIP: SpNavbar and Keplr connection
tendermint/vue pull request #156
Opened 2022-01-03 23:37 UTC by Matthews3301

2022-01-06 17:23 UTC, marinhoarthur requested changes
Points:

- Lack of components that are being used (`SpButton`)
- Not able to connect to Keplr (error)
- `SpNavbar` wrapping too many responsibilities. Split Keplr stuff into a dedicated component (`SpAcc` or smth)

And minors:

- Remove `depsLoaded` and overall cleaning
- Let's get closer to each other as far as code style goes #158 (refer to `SpTx`)
- Since icons were put into separate files let's use our agreed new folder structure (e.g.: src/components/ui)

2022-01-06 23:08 UTC, Matthews3301 commented
@marinhoarthur what error are you getting when connecting to Keplr? What does it say in the console?

2022-01-06 23:33 UTC, Matthews3301 commented
@marinhoarthur please check commit e89c2f4 for fixes related to your points.

2022-01-07 12:31 UTC, Matthews3301 commented
@marinhoarthur not sure why this is happening but all indenting is using tabs... Would it not be better to use double spaces? It looks better in GitHub preview.

2022-01-07 12:35 UTC, marinhoarthur commented
Pushed: 

- Took account stuff out of `SpNavbar` and put in `SpAcc` instead
- Moved the icons files around because rollup had a problem while loading those (we can tackle this later!)
- The `useKeplr` composable was updating component specific reactive stuff. Don't think this is desired. Why don't we use callbacks passed to the `connectToKeplr` (e.g.: onConnect, onError)?

2022-01-07 12:47 UTC, marinhoarthur commented
> @marinhoarthur not sure why this is happening but all indenting is using tabs... Would it not be better to use double spaces? It looks better in GitHub preview.

probably some code formatting tuning...

2022-01-07 20:05 UTC, marinhoarthur commented
Just [pushed](https://github.com/tendermint/vue/pull/156/commits/00fee5c3d95b2af248b74a3672306c2784ab71fc) changes tackling most of my comments above.

2022-01-07 20:11 UTC, marinhoarthur requested changes
See comments

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +		const state = reactive({
Let's use [this approach](https://github.com/tendermint/vue/blob/07ad9b921f73568febf1d3b29bad0d833c08add1/packages/vue/src/components/SpTx/SpTx.vue#L309) to increase typing capabilities?

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +			const offlineSigner = window.keplr.getOfflineSigner(chainId)
Since we now have `useKeplr` composable, better to move all keplr related stuff in there, right?

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +    const autoConnectToChain = async (chainId: string) => {
what's the purpose of auto connecting a chain?

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +      const chainId = $s.getters['common/env/chainId']
this should be a computed prop

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +      updateWalletData($s.getters['common/env/chainId'])
we need to set a listener to solve this #151

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +      const offlineSigner = window.keplr.getOfflineSigner(chainId)
like said before, keplr api should be exposed by `useKeplr`

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +      await $s.dispatch('common/wallet/connectWithKeplr', offlineSigner)
ideally let's have an action block listing all store actions

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAccountDropdown/SpAccountDropdown.vue
> +
let's keep this component simple and just emit `disconnect`, leaving spacc with the `signOut` dispatching job

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/composables/useKeplr.ts
> +export interface Amount {
these two interfaces are already implemented & exposed by `utils/interfaces`

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/composables/useKeplr.ts
> +            low: 0.01,
for the future: make these dynamic

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/composables/useKeplr.ts
> +            y.coinDecimals = 0
for the future: make these dynamic

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpNavbar/SpNavbar.vue
> +      links: props.links,
reactive over reactive, why?

2022-01-07 20:11 UTC, marinhoarthur commented on packages/vue/src/components/SpAcc/SpAcc.vue
> +		let state = reactive({
Let's type state as in [SpTx](https://github.com/tendermint/vue/blob/7960205087d62318209160dd88fae4cd2c580def/packages/vue/src/components/SpTx/SpTx.vue#L308) please!

2022-01-07 20:14 UTC, marinhoarthur commented
solves #151

2022-01-07 20:17 UTC, marinhoarthur commented on packages/vue/src/composables/useKeplr.ts
> +            low: 0.01,
related to #153

2022-01-07 20:31 UTC, marinhoarthur commented
`SpAcc` is a good candidate to have an enum as ui state as in [here](https://github.com/tendermint/vue/blob/7960205087d62318209160dd88fae4cd2c580def/packages/vue/src/components/SpTx/SpTx.vue#L291-L306). Having multiple booleanz getting together to express current ui state is hard to maintain.

2022-01-08 17:09 UTC, marinhoarthur approved these changes

2022-01-08 17:09 UTC, merged