fix: style in the token list (modal)
tendermint/vue pull request #257
Opened 2022-03-11 11:21 UTC by mihailmarcu

Closes: #242

2022-03-15 11:23 UTC, marinhoarthur requested changes
Shall we use what Vue is recommending?

![image](https://user-images.githubusercontent.com/3693700/158367450-5a5a46ad-96b4-40cd-bb9d-3f8daad6e129.png)

2022-03-15 11:25 UTC, fadeev commented
@darika-dev adding you as a reviewer, please, check out this PR 🙏

2022-03-15 11:39 UTC, mihailmarcu commented
Hey @here,
I removed the deprecated ::v-deep pseudo-class and used :deep() instead.

2022-03-21 13:16 UTC, marinhoarthur approved these changes

2022-03-25 13:52 UTC, merged